---
version: 3
tasks:
  clean: rm rss-feed-server.tar cover.html cover.out
  build:
    cmds:
      - docker build -t rss-feed-server .
      - docker image save localhost/rss-feed-server:latest > rss-feed-server.tar
